### ISSUE TITLE
Recording existing shortcut triggers it

### ISSUE THREAD

**Issue by jh247247** [acheronfail/apptivator#22]
Attempting to re-record a shortcut triggers the action to switch to that app instead of finishing recording.
On top of this, certain shortcuts cannot be fully recorded, like `Command+Shift+S`.

To replicate "strange behaviour"
1. Record a shortcut to an app, say `Command+Shift+R`
2. Try and change that shortcut to `Command+Shift+S`, this will record `Command+Shift` but fail to record the `S` (Possibly because of the `Command+S` system shortcut 🤔)
3. Give up and try and revert back to `Command+Shift+R`, you will switch to that app instead.

**Comment by acheronfail** [comment]
> Attempting to re-record a shortcut triggers the action to switch to that app instead of finishing recording.

This should now be fixed in 980f3bb - shortcuts won't fire if you're in the middle of recording a shortcut.

> On top of this, certain shortcuts cannot be fully recorded, like `Command+Shift+S`.

I can't replicate this on my machine, recording and using that command works fine for me. Can you provide any more information about it?

**Comment by acheronfail** [comment]
Keeping this open until we find a solution for your second issue.

**Comment by acheronfail** [comment]
I can't seem to replicate it, so I'll close this for now!
