### ISSUE TITLE
Feature: Option to choose between clicking and right-clicking menu icon

### ISSUE THREAD

**Issue by ghost** [acheronfail/apptivator#26]
Would be neat if there was an option to allow the user to decide whether clicking the menubar icon enables / disables Apptivator and right-clicking displays the menu OR if clicking the menubar icon displays the menu, and right-clicking or possibly a menu item enables / disables.

Just a thought, it seems a little un-natural to right click in order to configure the shortcuts when that is the main purpose of the app. 

Great / Useful app though, really enjoy it.

**Comment by acheronfail** [comment]
That unnatural workflow was the original reason I added the "Show/hide this window with shortcut" at the bottom of the configuration window, so the user could easily show/hide the window.

I was actually just thinking of doing this - but I couldn't decide where to put the UI setting for this. Should it be a checkbox in the window, or a menu item in the drop down menu?

@rubyframework any suggestions?

**Comment by acheronfail** [comment]
Still not sure about how to implement this in the UI, so for now it's been added as an experimental override in [v1.4.4](https://github.com/acheronfail/apptivator/releases/tag/1.4.4). Check the README for how to toggle them.
